# -*- coding: utf-8 -*-
"""train_explore_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gUFt7n7W8DDxfr5MyiFrDcH1haI891BC

# srnn-2afc on Colab GPU

Colab-ready version of `train_explore.ipynb`. Upload this file to [colab.research.google.com](https://colab.research.google.com) (File → Upload notebook), then **Runtime → Change runtime type → T4 GPU** before running.

**Why GPU works here but not on a Mac laptop:** this model runs entirely in `torch.double` (float64) — the surrogate-gradient spiking dynamics were written that way. Apple's Metal (`mps`) backend doesn't support float64 at all, so on a Mac this only runs on CPU. CUDA (what Colab's GPUs use) *does* support float64, so the exact same code that's CPU-only on a Mac runs on GPU here unmodified.

**Compatibility patch:** the repo pins `norse==0.0.3` (2021), which itself pins `torch==1.5.0` — no longer installable against a current CUDA/Colab environment. This notebook `pip install`s the latest `norse` instead and patches three files at runtime to restore the old API surface the repo's code expects. I diffed old vs. new norse source directly: the actual spiking-neuron math the repo hand-rolls in `lif_refrac_cell.py` is unchanged between versions — only two thin wrapper classes were reshaped upstream, plus one Python-dataclass compatibility fix. See the patch cell below for exactly what changes and why.
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone -q https://github.com/Jakexxh/srnn-2afc.git
# %cd srnn-2afc
!pip install -q norse absl-py tensorboard

import pathlib

repo = pathlib.Path(".")

compat_src = '''"""Compatibility shims restoring norse==0.0.3 APIs this repo was written against.

The repo pins norse==0.0.3 (2021); pip installs the latest norse instead. The
underlying spiking-neuron math this repo hand-rolls (lif_current_encoder,
compute_refractory_update, threshold, LIFState/LIFRefracState) is unchanged
between versions - only two thin nn.Module wrapper classes were removed/reshaped
upstream. Restoring their 0.0.3 behavior here keeps every other file in the repo
byte-for-byte identical to the original.
"""
import numpy as np
import torch
from norse.torch.functional.leaky_integrator import li_feed_forward_step, LIState, LIParameters


class LIFeedForwardCell(torch.nn.Module):
    def __init__(self, shape, p: LIParameters = LIParameters(), dt: float = 0.001):
        super().__init__()
        self.p = p
        self.dt = dt
        self.shape = shape

    def initial_state(self, batch_size, device, dtype=torch.float):
        return LIState(
            v=torch.zeros(batch_size, *self.shape, device=device, dtype=dtype),
            i=torch.zeros(batch_size, *self.shape, device=device, dtype=dtype),
        )

    def forward(self, input_tensor, s):
        return li_feed_forward_step(input_tensor, s, p=self.p, dt=self.dt)


class LegacyLIFRefracCellBase(torch.nn.Module):
    def __init__(self, input_size, hidden_size, p, dt: float = 0.001):
        super().__init__()
        self.input_weights = torch.nn.Parameter(
            torch.randn(hidden_size, input_size) / np.sqrt(input_size)
        )
        self.recurrent_weights = torch.nn.Parameter(
            torch.randn(hidden_size, hidden_size) / np.sqrt(hidden_size)
        )
        self.hidden_size = hidden_size
        self.p = p
        self.dt = dt
'''
(repo / "norse_compat.py").write_text(compat_src)

snn_pfc = repo / "snn_PFC.py"
text = snn_pfc.read_text()
assert "from norse.torch.module.leaky_integrator import LIFeedForwardCell" in text, "repo source changed upstream - patch needs updating"
text = text.replace(
    "from norse.torch.module.leaky_integrator import LIFeedForwardCell",
    "from norse_compat import LIFeedForwardCell",
)
snn_pfc.write_text(text)

lif_refrac = repo / "lif_refrac_cell.py"
text = lif_refrac.read_text()
assert "from norse.torch.module.lif_refrac import LIFRefracCell" in text, "repo source changed upstream - patch needs updating"
text = text.replace(
    "from norse.torch.module.lif_refrac import LIFRefracCell",
    "from norse_compat import LegacyLIFRefracCellBase as LIFRefracCell",
)
lif_refrac.write_text(text)

params = repo / "parameters.py"
text = params.read_text()
assert "from norse.torch.functional.lif_refrac import LIFRefracParameters" in text, "repo source changed upstream - patch needs updating"
assert "class EILIFRefracParameters(LIFRefracParameters):" in text, "repo source changed upstream - patch needs updating"
text = text.replace(
    "from norse.torch.functional.lif_refrac import LIFRefracParameters\nfrom dataclasses import dataclass",
    "from dataclasses import dataclass, field",
)
text = text.replace(
    "class EILIFRefracParameters(LIFRefracParameters):\n    lif: EILIFParameters = EILIFParameters()",
    "class EILIFRefracParameters:\n    lif: EILIFParameters = field(default_factory=EILIFParameters)",
)
params.write_text(text)

print("patch applied")

import sys, os
sys.path.insert(0, os.path.abspath('.'))

import numpy as np
import torch
import matplotlib.pyplot as plt

from norse.torch.functional.lif import LIFParameters
from parameters import EILIFRefracParameters, EILIFParameters
from data_generator import DataGenerator
from snn_PFC import SNN
from model import Model

torch.manual_seed(0)
np.random.seed(0)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print('device:', device)
if device.type != 'cuda':
    print("No GPU detected - go to Runtime > Change runtime type > T4 GPU, then Runtime > Restart session.")

"""## 1. The task: generate 2AFC trials

Each trial has 5 input channels over time: `Aud-Right`, `Aud-Left`, `Vis-Right`, `Vis-Left`, and a `Cueing` channel that tells the network which modality (audio or visual) is relevant on this trial. The network has to report the side (left/right) indicated by the *cued* modality, ignoring the other one — a context-dependent 2-alternative forced choice.
"""

dt = 0.002  # seconds per simulation timestep

trial_setting = {
    'fixation': 0.2,
    'cueing': 0.1,
    'cueing_delay': 0.4,
    'stimulus': 0.1,
    'decision': 0.0,
}

batch_size = 64  # paper default; Colab GPU handles this comfortably

data_loader = DataGenerator(
    batch_size,
    trial_setting=trial_setting,
    p=LIFParameters(),
    cueing_context_num=1,  # 1 = plain 2AFC; 2 adds a second cueing-context rule set
    dt=dt,
)
data_loader.generate_all_trials()
print(f'{len(data_loader.trials)} distinct trial types, sequence length {data_loader.seq_len} steps '
      f'({data_loader.seq_len * dt:.2f}s per trial)')

# Look at one example trial's raw input spikes (in place of data_generator.py's plot_trials, which saves to disk)
trial, ground_truth, desc = data_loader.trials[0]
inputs = trial.to_sparse().coalesce()
t_idx, ch_idx = inputs.indices()

fig, ax = plt.subplots(figsize=(10, 3))
ax.scatter(t_idx, ch_idx, marker='|', color='black')
ax.set_yticks([0, 1, 2, 3, 4])
ax.set_yticklabels(['Aud-Right', 'Aud-Left', 'Vis-Right', 'Vis-Left', 'Cueing'])
ax.set_xlabel('timestep')
ax.set_title(f'example trial: {desc}  (ground_truth={ground_truth})')
plt.tight_layout()
plt.show()

"""## 2. Build the network

`SNN_LIFCell` is a recurrent layer of leaky integrate-and-fire neurons with:
- **Dale's law**: 80% of units are excitatory, 20% inhibitory (`ei_ratio`), enforced by masking the sign of outgoing recurrent weights.
- **Spike-frequency adaptation (SFA)**: a subset of units (`sfa_ratio`) have a rising spike threshold driven by their own recent firing, giving them longer time constants.
- Independent per-neuron voltage/current noise (a random walk in the base current, white noise in voltage) so the dynamics aren't perfectly deterministic.

Its output feeds a linear readout into a small non-spiking leaky-integrator layer (`fc_out` + `out`), which is what gets decoded into left/right.

`hidden_size=500` below is the paper's actual default — worth using now that a GPU is available, since a bigger recurrent matmul per timestep is exactly where GPU parallelism helps most.
"""

hidden_size = 500  # paper default

model_parameters = EILIFRefracParameters(
    lif=EILIFParameters(
        tau_ex_syn_inv=torch.as_tensor(1 / (35 * 1e-3), dtype=torch.double),
        tau_ih_syn_inv=torch.as_tensor(1 / (40 * 1e-3), dtype=torch.double),
        tau_mem_inv=torch.as_tensor(1 / (20 * 1e-3), dtype=torch.double),
        tau_adaptation_inv=torch.as_tensor(1 / (400 * 1e-3), dtype=torch.double),
        R=torch.as_tensor(10 * 1e-3, dtype=torch.double),
        v_leak=torch.as_tensor(-65.0 * 1e-3, dtype=torch.double),
        v_th=torch.as_tensor(-50.0 * 1e-3, dtype=torch.double),
        v_reset=torch.as_tensor(-65.0 * 1e-3, dtype=torch.double),
        dale=True,
        ei_ratio=0.8,
        beta=1.6,
        sfa_ratio=0.25,
        rho=1.5,
        current_base_scale=0.041,
        current_base_lower=1.8,
        current_base_upper=2.4,
        current_base_mu=2.0,
        current_base_sigma=0.1,
        rand_current_std=0.002,
        rand_voltage_std=0.004,
        rand_walk_alpha=1.0,
        method='super',
        alpha=1000.0,
    ),
    rho_reset=torch.as_tensor(3.0),
)

loss_step = 5  # decode from the average of the final 5 timesteps

model = Model(
    snn=SNN(p=model_parameters, hidden_size=hidden_size, output_size=2, dt=dt, device=device),
    decoder='mse',
    loss_step=loss_step,
).to(device)

n_params = sum(p.numel() for p in model.parameters())
exc_size = int(hidden_size * model_parameters.lif.ei_ratio)
print(f'{n_params} trainable parameters, {hidden_size} hidden units '
      f'({exc_size} excitatory / {hidden_size - exc_size} inhibitory)')

"""## 3. Train

This reimplements the core of `main.py`'s `train()`/`test()` loop directly (skipping `absl` flags and the TensorBoard writer, which don't suit a notebook), so it's the exact same math, just easier to read and step through here.

`epochs=100`, `batch_num=200` below match the paper's defaults. Checkpoints save to `/content/srnn-2afc/checkpoints/` every 10 epochs, since free Colab GPU sessions can disconnect - if that happens, rerun the setup/patch cells, then reload the latest checkpoint instead of restarting training from scratch.
"""

from google.colab import drive
drive.mount('/content/drive')

import time

epochs = 60        # paper default
batch_num = 200      # batches per epoch; paper default
learning_rate = 3e-4
fr_reg_value = 1e-9  # firing-rate regularization, matches main.py default (keeps units from firing at ceiling)
checkpoint_every = 10

os.makedirs('checkpoints', exist_ok=True)
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

train_losses, train_accs, test_losses, test_accs = [], [], [], []

def run_batch(train: bool):
    trials, tgs, _ = data_loader.get_batch()
    tgs = tgs.unsqueeze(1).repeat((1, loss_step, 1)).double()
    _, ground_truth = torch.max(tgs[:, -1], 1)
    trials, tgs, ground_truth = trials.to(device), tgs.to(device), ground_truth.to(device)

    output = model(trials)
    loss = torch.nn.functional.mse_loss(output, tgs)

    if train:
        bin_size = 5
        fr = torch.mean(model.snn.recording.lif0.z.permute(2, 0, 1), dim=-1)
        fr = torch.sum(torch.reshape(torch.mean(fr, axis=0), (-1, bin_size)), axis=1) / (dt * bin_size)
        fr_loss = fr_reg_value * torch.nn.functional.mse_loss(fr, target=torch.zeros_like(fr), reduction='sum')
        loss = loss + fr_loss

    pred = torch.argmax(output[:, -1], 1)
    acc = (ground_truth == pred).float().mean().item()
    return loss, acc

t0 = time.time()
for epoch in range(epochs):
    model.train()
    epoch_losses, epoch_accs = [], []
    for _ in range(batch_num):
        optimizer.zero_grad()
        loss, acc = run_batch(train=True)
        loss.backward()
        optimizer.step()
        epoch_losses.append(loss.item())
        epoch_accs.append(acc)

    model.eval()
    with torch.no_grad():
        t_loss, t_acc = zip(*[run_batch(train=False) for _ in range(10)])
        t_loss = [l.item() for l in t_loss]

    train_losses.append(np.mean(epoch_losses))
    train_accs.append(np.mean(epoch_accs))
    test_losses.append(np.mean(t_loss))
    test_accs.append(np.mean(t_acc))

    elapsed = time.time() - t0
    print(f'epoch {epoch+1:>3}/{epochs}  train loss {train_losses[-1]:.4f} acc {train_accs[-1]:.2f}  |  '
          f'test loss {test_losses[-1]:.4f} acc {test_accs[-1]:.2f}  |  {elapsed:.0f}s elapsed')

    if (epoch + 1) % checkpoint_every == 0 or epoch == epochs - 1:
        torch.save(
            {'epoch': epoch, 'model_state_dict': model.state_dict(), 'optimizer_state_dict': optimizer.state_dict()},
            f'checkpoints/snn_PFC-{epoch+1}.pt',
        )

fig, ax = plt.subplots(1, 2, figsize=(11, 3.5))
ax[0].plot(train_losses, label='train')
ax[0].plot(test_losses, label='test')
ax[0].set_title('loss'); ax[0].set_xlabel('epoch'); ax[0].legend()

ax[1].plot(train_accs, label='train')
ax[1].plot(test_accs, label='test')
ax[1].axhline(0.5, color='gray', linestyle='--', linewidth=1, label='chance')
ax[1].set_title('accuracy'); ax[1].set_xlabel('epoch'); ax[1].legend()
plt.tight_layout()
plt.show()

"""## 2b. Or: skip training, load the paper's pretrained checkpoint

The repo's [README](README.md) links a pretrained checkpoint (`snn_PFC-final.pt`, trained for 60 epochs at the paper's `hidden_size=500`) on Google Drive. Loading it drops straight into a network that already solves the task — useful for jumping straight to section 4's internals-inspection without waiting for training.

Run this cell **instead of** section 3's training cells if you just want to explore an already-trained network; skip it if you want to train from scratch yourself.
"""

import subprocess

ckpt_path = 'checkpoints/snn_PFC-final.pt'
os.makedirs('checkpoints', exist_ok=True)
if not os.path.exists(ckpt_path):
    subprocess.run([
        'curl', '-sL',
        'https://drive.google.com/uc?id=1uqPcKgggxp0ExwxK1j16OHgSwcPEvlcR&export=download',
        '-o', ckpt_path,
    ], check=True)

# the released checkpoint was trained at the paper's hidden_size=500; must match to load
hidden_size = 500
exc_size = int(hidden_size * model_parameters.lif.ei_ratio)

model = Model(
    snn=SNN(p=model_parameters, hidden_size=hidden_size, output_size=2, dt=dt, device=device),
    decoder='mse',
    loss_step=loss_step,
).to(device)

ckpt = torch.load(ckpt_path, map_location=device, weights_only=False)
model.load_state_dict(ckpt['model_state_dict'])
model.eval()
print(f"loaded checkpoint from epoch {ckpt['epoch']}, hidden_size={hidden_size}")

model.eval()

"""## 4. Look inside the trained network

`model.snn.recording` was populated during the last forward pass with every timestep's hidden-layer spikes/voltage/current and readout voltage/current — this is where the actual model internals become visible.
"""

# Run one fixed (non-random) trial through the trained model and inspect its internal dynamics
model.eval()
with torch.no_grad():
    trials, tgs, desc = data_loader.get_batch(if_rand=False)
    trials = trials.to(device)
    _ = model(trials)

trial_i = 0  # which trial in the batch to visualize
rec = model.snn.recording

fig, ax = plt.subplots(4, 1, figsize=(11, 10), sharex=True)

z = rec.lif0.z[:, trial_i, :].cpu().numpy()
spike_t, spike_n = np.nonzero(z)
ax[0].scatter(spike_t, spike_n, marker='|', s=8, color='black')
ax[0].axhline(exc_size, color='red', linestyle='--', linewidth=1)
ax[0].set_ylabel('hidden unit')
ax[0].set_title(f'hidden-layer spike raster (below red line = excitatory, above = inhibitory)  trial: {desc[trial_i]}')

ax[1].plot(rec.lif0.v[:, trial_i, :5].cpu().numpy())
ax[1].set_ylabel('v (V)')
ax[1].set_title('membrane voltage, first 5 hidden units')

ax[2].plot(rec.readout.v[:, trial_i, :].cpu().numpy())
ax[2].set_ylabel('v (a.u.)')
ax[2].legend(['side 0', 'side 1'])
ax[2].set_title('readout voltage (this is what gets decoded into the choice)')

fr = z.mean(axis=0) / dt
ax[3].bar(np.arange(hidden_size), fr, color=['tab:red' if i < exc_size else 'tab:blue' for i in range(hidden_size)])
ax[3].set_ylabel('Hz'); ax[3].set_xlabel('hidden unit (red=excitatory, blue=inhibitory)')
ax[3].set_title('per-unit firing rate on this trial')

plt.tight_layout()
plt.show()

# Recurrent weight matrix, sorted E/I — this is the Dale's-law structure the network learned around
w_rec = (torch.abs(model.snn.l1.recurrent_weights) * model.snn.l1.recurrent_weights_mask).detach().cpu().numpy()

plt.figure(figsize=(5, 5))
plt.imshow(w_rec, cmap='viridis')
plt.axhline(exc_size - 0.5, color='red', linewidth=1)
plt.axvline(exc_size - 0.5, color='red', linewidth=1)
plt.colorbar(label='|weight|')
plt.xlabel('presynaptic unit'); plt.ylabel('postsynaptic unit')
plt.title('recurrent weights (magnitude), E/I split marked in red')
plt.tight_layout()
plt.show()

"""## Getting checkpoints off Colab

Free Colab instances are ephemeral — anything in `/content` disappears when the runtime recycles. Either download `checkpoints/snn_PFC-*.pt` directly (files panel on the left, or `from google.colab import files; files.download(...)`), or mount Google Drive at the top of this notebook (`from google.colab import drive; drive.mount('/content/drive')`) and point `checkpoints/` at a Drive path before training so it survives disconnects.

## Where to go from here

- Try `cueing_context_num=2` in the `DataGenerator` cell to add the second context-cueing rule set from the paper.
- Compare `dale=True` vs `dale=False` in `EILIFParameters` to see how much Dale's-law structure matters for solving the task.
- `results_visualization.py` and `ResultsVisualization.ipynb` (in the cloned repo, `/content/srnn-2afc/`) have the paper's actual population-level analyses (PCA of trajectories, rule-dependent sequences, etc.) — worth a look now that you have a real checkpoint.

# Training vanilla RNN (old)

The following section defines the non-leaky RNN model -- skip to leaky RNN
"""

class VanillaRNN(torch.nn.Module):
    """The simplest possible alternative to SNN_LIFCell: a standard Elman RNN
    (tanh nonlinearity, continuous-valued hidden state) with a linear readout.
    No spiking, no Dale's-law E/I split, no spike-frequency adaptation, no
    refractory period, no injected voltage/current noise - just a recurrent
    layer mapping the same 5-channel input to the same 2-choice output."""

    def __init__(self, input_size, hidden_size, output_size, loss_step, rho=1.5):
        super().__init__()
        self.rnn = torch.nn.RNN(input_size, hidden_size, nonlinearity='tanh')
        self.readout = torch.nn.Linear(hidden_size, output_size)
        self.loss_step = loss_step
        self.recording = None  # populated on each forward() call, mirrors model.snn.recording

        with torch.no_grad():
            w_hh = self.rnn.weight_hh_l0
            spectral_radius = torch.linalg.eigvals(w_hh).abs().max()
            w_hh.mul_(rho / spectral_radius)

    def forward(self, x):
        # x: (seq_len, batch, input_size) - same layout DataGenerator produces
        h_seq, _ = self.rnn(x)                       # (seq_len, batch, hidden_size)
        self.recording = h_seq.detach()               # exposed for analysis (e.g. rule-tuning section)
        out = self.readout(h_seq)                     # (seq_len, batch, output_size)
        return out[-self.loss_step:].transpose(1, 0)   # (batch, loss_step, output_size), same shape Model() produces

vanilla_hidden_size = 500  # match whatever hidden_size you used for the spiking model above, for a fair comparison

vanilla_model = VanillaRNN(
    input_size=5, hidden_size=vanilla_hidden_size, output_size=2, loss_step=loss_step,
    rho=model_parameters.lif.rho,  # same spectral-radius target as the SNN's recurrent weights
).to(device).double()  # match the spiking SNN's float64 precision

n_vanilla_params = sum(p.numel() for p in vanilla_model.parameters())
print(f"{n_vanilla_params} trainable parameters, {vanilla_hidden_size} hidden units (no E/I split, no Dale's law)")

vanilla_epochs = 5      # match section 3's epochs for a fair comparison
vanilla_batch_num = 200   # match section 3's batch_num
vanilla_batch_size = 200
vanilla_lr = 3e-4

# separate DataGenerator so the vanilla RNN can use its own batch_size, independent
# of the spiking model's data_loader (same task/trial_setting/dt, just its own batches)
vanilla_data_loader = DataGenerator(
    vanilla_batch_size, trial_setting=trial_setting, p=LIFParameters(), cueing_context_num=1, dt=dt,
)
vanilla_data_loader.generate_all_trials()

vanilla_optimizer = torch.optim.Adam(vanilla_model.parameters(), lr=vanilla_lr)

def run_batch_vanilla(train: bool):
    trials, tgs, _ = vanilla_data_loader.get_batch()
    tgs = tgs.unsqueeze(1).repeat((1, loss_step, 1)).double()
    _, ground_truth = torch.max(tgs[:, -1], 1)
    trials, tgs, ground_truth = trials.to(device).double(), tgs.to(device), ground_truth.to(device)

    output = vanilla_model(trials)
    loss = torch.nn.functional.mse_loss(output, tgs)

    pred = torch.argmax(output[:, -1], 1)
    acc = (ground_truth == pred).float().mean().item()
    return loss, acc

vanilla_train_losses, vanilla_train_accs, vanilla_test_losses, vanilla_test_accs = [], [], [], []

for epoch in range(vanilla_epochs):
    vanilla_model.train()
    epoch_losses, epoch_accs = [], []
    for _ in range(vanilla_batch_num):
        vanilla_optimizer.zero_grad()
        loss, acc = run_batch_vanilla(train=True)
        loss.backward()
        vanilla_optimizer.step()
        epoch_losses.append(loss.item())
        epoch_accs.append(acc)

    vanilla_model.eval()
    with torch.no_grad():
        t_loss, t_acc = zip(*[run_batch_vanilla(train=False) for _ in range(10)])
        t_loss = [l.item() for l in t_loss]

    vanilla_train_losses.append(np.mean(epoch_losses))
    vanilla_train_accs.append(np.mean(epoch_accs))
    vanilla_test_losses.append(np.mean(t_loss))
    vanilla_test_accs.append(np.mean(t_acc))

    print(f'epoch {epoch+1:>3}/{vanilla_epochs}  train loss {vanilla_train_losses[-1]:.4f} acc {vanilla_train_accs[-1]:.2f}  |  '
          f'test loss {vanilla_test_losses[-1]:.4f} acc {vanilla_test_accs[-1]:.2f}')

fig, ax = plt.subplots(1, 2, figsize=(11, 3.5))

ax[0].plot(vanilla_test_losses, label='vanilla RNN (test)', color='tab:orange')
ax[1].plot(vanilla_test_accs, label='vanilla RNN (test)', color='tab:orange')

if 'test_losses' in globals() and 'test_accs' in globals():
    ax[0].plot(test_losses, label='spiking SRNN (test)', color='tab:blue')
    ax[1].plot(test_accs, label='spiking SRNN (test)', color='tab:blue')
else:
    print("Run section 3's training cell first to overlay the spiking model's curves here too.")

ax[0].set_title('test loss'); ax[0].set_xlabel('epoch'); ax[0].legend()
ax[1].axhline(0.5, color='gray', linestyle=':', linewidth=1, label='chance')
ax[1].set_title('test accuracy'); ax[1].set_xlabel('epoch'); ax[1].legend()
plt.tight_layout()
plt.show()

print(f'vanilla RNN:  {n_vanilla_params} params, final test acc {vanilla_test_accs[-1]:.1%}')
if 'test_accs' in globals() and 'n_params' in globals():
    print(f'spiking SRNN: {n_params} params, final test acc {test_accs[-1]:.1%}')

# Pick one example trial per named condition
conditions = {
    'Aud/Right': lambda d: d['c'] == 0 and d['aud'] == 0,
    'Aud/Left':  lambda d: d['c'] == 0 and d['aud'] == 1,
    'Vis/Right': lambda d: d['c'] == 1 and d['light'] == 0,
    'Vis/Left':  lambda d: d['c'] == 1 and d['light'] == 1,
}

example_trials, example_descs = [], []
for name, match in conditions.items():
    for trial, gt, desc in vanilla_data_loader.trials:
        if match(desc):
            example_trials.append(trial)
            example_descs.append(desc)
            break

demo_inputs = torch.stack(example_trials, dim=1).double().to(device)  # (seq_len, 4, 5)

vanilla_model.eval()
with torch.no_grad():
    _ = vanilla_model(demo_inputs)
    demo_hidden = vanilla_model.recording                    # (seq_len, 4, hidden_size)
    demo_outputs_full = vanilla_model.readout(demo_hidden)     # (seq_len, 4, 2), unsliced by loss_step

demo_hidden_np = demo_hidden.cpu().numpy()
demo_outputs_np = demo_outputs_full.cpu().numpy()
unit_indices = np.arange(min(10, vanilla_hidden_size))  # a handful of example hidden units

# epoch boundaries (in timesteps) from trial_setting, for the vertical markers below
epoch_bounds = {}
t = 0
for epoch_name in ['fixation', 'cueing', 'cueing_delay', 'stimulus', 'decision']:
    steps = round(trial_setting[epoch_name] / dt)
    epoch_bounds[epoch_name] = (t, t + steps)
    t += steps

fig, axes = plt.subplots(len(conditions), 2, figsize=(12, 3 * len(conditions)), sharex=True)
for row, (name, desc) in enumerate(zip(conditions.keys(), example_descs)):
    ax_hidden, ax_out = axes[row]

    ax_hidden.plot(demo_hidden_np[:, row, unit_indices], linewidth=0.8)
    ax_hidden.set_ylabel(f'{name}\nhidden activity')

    ax_out.plot(demo_outputs_np[:, row, 0], label='output 0 (right)')
    ax_out.plot(demo_outputs_np[:, row, 1], label='output 1 (left)')
    ax_out.set_ylabel('readout')
    if row == 0:
        ax_out.legend(loc='upper right', fontsize=8)

    for ax in (ax_hidden, ax_out):
        for start, end in epoch_bounds.values():
            if start == 0 or end == start:
                continue
            ax.axvline(start, color='gray', linestyle=':', linewidth=1)

axes[0, 0].set_title('example hidden units')
axes[0, 1].set_title('output channels')
axes[-1, 0].set_xlabel('timestep')
axes[-1, 1].set_xlabel('timestep')
fig.suptitle('Vanilla RNN: hidden activity and outputs, one example trial per condition')
plt.tight_layout()
plt.show()

"""# Leaky vanilla (current)"""

class VanillaRNN(torch.nn.Module):
    """Alternative to SNN_LIFCell: a continuous-time ("leaky") RNN with tanh nonlinearity -
    no spiking, no Dale's-law E/I split, no spike-frequency adaptation, no refractory period,
    no injected voltage/current noise. Unlike a standard hard-update Elman RNN, this keeps one
    piece of the SNN's biology: membrane leak. Each step blends in only `alpha` of the new tanh
    update and retains (1-alpha) of the previous state - alpha = dt/tau_mem, matched to the SNN's
    own membrane time constant, so this comparison isolates spiking vs. continuous dynamics as
    the one varying factor, rather than silently conflating it with leaky vs. non-leaky too."""

    def __init__(self, input_size, hidden_size, output_size, loss_step, alpha, rho=1.5):
        super().__init__()
        self.hidden_size = hidden_size
        self.loss_step = loss_step
        self.alpha = alpha  # leak fraction per timestep: (1-alpha) retained, alpha new update
        self.recording = None  # populated on each forward() call, mirrors model.snn.recording

        self.input_weights = torch.nn.Parameter(torch.randn(hidden_size, input_size) / input_size ** 0.5)
        self.bias = torch.nn.Parameter(torch.zeros(hidden_size))
        self.recurrent_weights = torch.nn.Parameter(torch.empty(hidden_size, hidden_size))
        self.readout = torch.nn.Linear(hidden_size, output_size)

        # Match SNN_LIFCell's recurrent weight init (lif_refrac_cell.py): rescale so the
        # recurrent matrix's spectral radius equals rho before training starts, instead of an
        # arbitrary uncontrolled default. Without this the SNN gets a principled dynamical
        # starting point the vanilla RNN doesn't, confounding any gap between the two with
        # initialization quality rather than the architectural differences being compared.
        with torch.no_grad():
            w = torch.randn(hidden_size, hidden_size) / hidden_size ** 0.5
            spectral_radius = torch.linalg.eigvals(w).abs().max()
            self.recurrent_weights.copy_(w * (rho / spectral_radius))

    def forward(self, x):
        # x: (seq_len, batch, input_size) - same layout DataGenerator produces
        seq_len, batch_size, _ = x.shape
        h = torch.zeros(batch_size, self.hidden_size, dtype=x.dtype, device=x.device)
        outputs, hs = [], []
        for t in range(seq_len):
            candidate = torch.tanh(x[t] @ self.input_weights.T + h @ self.recurrent_weights.T + self.bias)
            h = (1 - self.alpha) * h + self.alpha * candidate
            hs.append(h.detach())
            outputs.append(self.readout(h))
        out = torch.stack(outputs)                    # (seq_len, batch, output_size)
        self.recording = torch.stack(hs)               # (seq_len, batch, hidden_size), exposed for analysis
        return out[-self.loss_step:].transpose(1, 0)    # (batch, loss_step, output_size), same shape Model() produces


vanilla_hidden_size = 500  # match whatever hidden_size you used for the spiking model above, for a fair comparison
vanilla_alpha = dt * model_parameters.lif.tau_mem_inv.item()  # leak fraction per step, matched to the SNN's tau_mem

vanilla_model = VanillaRNN(
    input_size=5, hidden_size=vanilla_hidden_size, output_size=2, loss_step=loss_step,
    alpha=vanilla_alpha, rho=model_parameters.lif.rho,
).to(device).double()  # match the spiking SNN's float64 precision

n_vanilla_params = sum(p.numel() for p in vanilla_model.parameters())
print(f"{n_vanilla_params} trainable parameters, {vanilla_hidden_size} hidden units "
      f"(no E/I split, no Dale's law, leaky with alpha={vanilla_alpha:.3f} matching the SNN's tau_mem)")

"""Optional: load in checkpoint, or skip to training"""

vanilla_ckpt_path = '/content/drive/MyDrive/vanilla_rnn.pt'  # <-- update to wherever you have copied the checkpoint

vanilla_ckpt = torch.load(vanilla_ckpt_path, map_location=device, weights_only=False)

# reconstruct the exact architecture from the checkpoint's own config, rather than assuming
# it matches whatever hidden_size/alpha/rho happen to be set above
cfg = vanilla_ckpt['config']
vanilla_hidden_size = cfg['hidden_size']
vanilla_alpha = cfg['alpha']

vanilla_model = VanillaRNN(
    input_size=cfg['input_size'], hidden_size=vanilla_hidden_size, output_size=cfg['output_size'],
    loss_step=cfg.get('loss_step', loss_step), alpha=vanilla_alpha, rho=cfg.get('rho', 1.5),
).to(device).double()
vanilla_model.load_state_dict(vanilla_ckpt['model_state_dict'])
vanilla_model.eval()

n_vanilla_params = sum(p.numel() for p in vanilla_model.parameters())
print(f"loaded vanilla RNN checkpoint from {vanilla_ckpt_path} "
      f"({vanilla_ckpt.get('model_class', 'VanillaRNN')}), {n_vanilla_params} trainable parameters, "
      f"{vanilla_hidden_size} hidden units, alpha={vanilla_alpha:.3f}")

vanilla_epochs = 10      # match section 3's epochs for a fair comparison
vanilla_batch_num = 200   # match section 3's batch_num
vanilla_batch_size = 64
vanilla_lr = 1e-4

# separate DataGenerator so the vanilla RNN can use its own batch_size, independent
# of the spiking model's data_loader (same task/trial_setting/dt, just its own batches)
vanilla_data_loader = DataGenerator(
    vanilla_batch_size, trial_setting=trial_setting, p=LIFParameters(), cueing_context_num=1, dt=dt,
)
vanilla_data_loader.generate_all_trials()

vanilla_optimizer = torch.optim.Adam(vanilla_model.parameters(), lr=vanilla_lr)

def run_batch_vanilla(train: bool):
    trials, tgs, _ = vanilla_data_loader.get_batch()
    tgs = tgs.unsqueeze(1).repeat((1, loss_step, 1)).double()
    _, ground_truth = torch.max(tgs[:, -1], 1)
    trials, tgs, ground_truth = trials.to(device).double(), tgs.to(device), ground_truth.to(device)

    output = vanilla_model(trials)
    loss = torch.nn.functional.mse_loss(output, tgs)

    pred = torch.argmax(output[:, -1], 1)
    acc = (ground_truth == pred).float().mean().item()
    return loss, acc

vanilla_train_losses, vanilla_train_accs, vanilla_test_losses, vanilla_test_accs = [], [], [], []

for epoch in range(vanilla_epochs):
    vanilla_model.train()
    epoch_losses, epoch_accs = [], []
    for _ in range(vanilla_batch_num):
        vanilla_optimizer.zero_grad()
        loss, acc = run_batch_vanilla(train=True)
        loss.backward()
        vanilla_optimizer.step()
        epoch_losses.append(loss.item())
        epoch_accs.append(acc)

    vanilla_model.eval()
    with torch.no_grad():
        t_loss, t_acc = zip(*[run_batch_vanilla(train=False) for _ in range(10)])
        t_loss = [l.item() for l in t_loss]

    vanilla_train_losses.append(np.mean(epoch_losses))
    vanilla_train_accs.append(np.mean(epoch_accs))
    vanilla_test_losses.append(np.mean(t_loss))
    vanilla_test_accs.append(np.mean(t_acc))

    print(f'epoch {epoch+1:>3}/{vanilla_epochs}  train loss {vanilla_train_losses[-1]:.4f} acc {vanilla_train_accs[-1]:.2f}  |  '
          f'test loss {vanilla_test_losses[-1]:.4f} acc {vanilla_test_accs[-1]:.2f}')

"""# Training vanilla RNN with Dale's law (old)

Following code defines model without leaky units
"""

class VanillaRNNDale(torch.nn.Module):
    """VanillaRNN + Dale's law: each hidden unit is fixed as purely excitatory
    or purely inhibitory in its outgoing recurrent weights (sign fixed by cell
    type, only magnitude learned) - matching SNN_LIFCell's recurrent_weights_dale
    (lif_refrac_cell.py). Only excitatory units project to the readout, matching
    the SNN's read_out_mask; inhibitory units still fully drive the recurrent
    dynamics. Same spectral-radius-rho init as VanillaRNN, applied to the raw
    pre-Dale-sign matrix (same convention lif_refrac_cell.py itself uses)."""

    def __init__(self, input_size, hidden_size, output_size, loss_step, rho=1.5, ei_ratio=0.8):
        super().__init__()
        self.hidden_size = hidden_size
        self.exc_size = int(hidden_size * ei_ratio)
        self.loss_step = loss_step
        self.recording = None  # populated on each forward() call, mirrors model.snn.recording

        self.input_weights = torch.nn.Parameter(torch.randn(hidden_size, input_size) / input_size ** 0.5)
        self.bias = torch.nn.Parameter(torch.zeros(hidden_size))
        self.recurrent_weights = torch.nn.Parameter(torch.empty(hidden_size, hidden_size))
        self.readout = torch.nn.Linear(hidden_size, output_size)

        with torch.no_grad():
            w = torch.randn(hidden_size, hidden_size) / hidden_size ** 0.5
            spectral_radius = torch.linalg.eigvals(w).abs().max()
            self.recurrent_weights.copy_(w * (rho / spectral_radius))

        # fixed sign per presynaptic unit: +1 excitatory, scaled negative inhibitory
        # (scaling balances total E vs I drive, same idea as the SNN's dale_vec)
        dale_sign = torch.ones(hidden_size)
        dale_sign[self.exc_size:] = -ei_ratio / (1 - ei_ratio)
        self.register_buffer('dale_sign', dale_sign)
        self.register_buffer('no_self_mask', 1 - torch.eye(hidden_size))

        readout_mask = torch.ones(hidden_size)
        readout_mask[self.exc_size:] = 0  # only excitatory units project downstream
        self.register_buffer('readout_mask', readout_mask)

    def effective_recurrent_weights(self):
        # magnitude only - Dale's law fixes the sign, gradient descent only learns |w|
        w = torch.abs(self.recurrent_weights) * self.no_self_mask
        return w * self.dale_sign.unsqueeze(0)

    def forward(self, x):
        seq_len, batch_size, _ = x.shape
        h = torch.zeros(batch_size, self.hidden_size, dtype=x.dtype, device=x.device)
        w_rec = self.effective_recurrent_weights()
        outputs, hs = [], []
        for t in range(seq_len):
            a = x[t] @ self.input_weights.T + h @ w_rec.T + self.bias
            h = torch.tanh(a)
            hs.append(h.detach())
            outputs.append(self.readout(h * self.readout_mask))
        out = torch.stack(outputs)                    # (seq_len, batch, output_size)
        self.recording = torch.stack(hs)               # (seq_len, batch, hidden_size), exposed for analysis
        return out[-self.loss_step:].transpose(1, 0)    # (batch, loss_step, output_size)

dale_hidden_size = vanilla_hidden_size  # match the plain vanilla RNN's size for a fair 3-way comparison

dale_model = VanillaRNNDale(
    input_size=5, hidden_size=dale_hidden_size, output_size=2, loss_step=loss_step,
    rho=model_parameters.lif.rho, ei_ratio=model_parameters.lif.ei_ratio,
).to(device).double()

n_dale_params = sum(p.numel() for p in dale_model.parameters())
dale_exc_size = dale_model.exc_size
print(f"{n_dale_params} trainable parameters, {dale_hidden_size} hidden units "
      f"({dale_exc_size} excitatory / {dale_hidden_size - dale_exc_size} inhibitory)")

vanilla_epochs = 5      # match section 3's epochs for a fair comparison
vanilla_batch_num = 200   # match section 3's batch_num

vanilla_lr = 3e-4
# reuses vanilla_data_loader / vanilla_epochs / vanilla_batch_num / vanilla_lr from section 5,
# so this is trained on the same data with the same budget as the plain vanilla RNN
dale_optimizer = torch.optim.Adam(dale_model.parameters(), lr=vanilla_lr)

def run_batch_dale(train: bool):
    trials, tgs, _ = vanilla_data_loader.get_batch()
    tgs = tgs.unsqueeze(1).repeat((1, loss_step, 1)).double()
    _, ground_truth = torch.max(tgs[:, -1], 1)
    trials, tgs, ground_truth = trials.to(device).double(), tgs.to(device), ground_truth.to(device)

    output = dale_model(trials)
    loss = torch.nn.functional.mse_loss(output, tgs)

    pred = torch.argmax(output[:, -1], 1)
    acc = (ground_truth == pred).float().mean().item()
    return loss, acc

dale_train_losses, dale_train_accs, dale_test_losses, dale_test_accs = [], [], [], []

for epoch in range(vanilla_epochs):
    dale_model.train()
    epoch_losses, epoch_accs = [], []
    for _ in range(vanilla_batch_num):
        dale_optimizer.zero_grad()
        loss, acc = run_batch_dale(train=True)
        loss.backward()
        dale_optimizer.step()
        epoch_losses.append(loss.item())
        epoch_accs.append(acc)

    dale_model.eval()
    with torch.no_grad():
        t_loss, t_acc = zip(*[run_batch_dale(train=False) for _ in range(10)])
        t_loss = [l.item() for l in t_loss]

    dale_train_losses.append(np.mean(epoch_losses))
    dale_train_accs.append(np.mean(epoch_accs))
    dale_test_losses.append(np.mean(t_loss))
    dale_test_accs.append(np.mean(t_acc))

    print(f'epoch {epoch+1:>3}/{vanilla_epochs}  train loss {dale_train_losses[-1]:.4f} acc {dale_train_accs[-1]:.2f}  |  '
          f'test loss {dale_test_losses[-1]:.4f} acc {dale_test_accs[-1]:.2f}')

"""# Leaky vanila with Dale (current)"""

class VanillaRNNDale(torch.nn.Module):
    """VanillaRNN + Dale's law, and nothing else - still leaky (same alpha=dt/tau_mem as
    VanillaRNN, matched to the SNN's membrane time constant), still no spiking/adaptation/
    refractory period/injected noise. Each hidden unit is fixed as either purely excitatory or
    purely inhibitory (`ei_ratio=0.8`, matching the SNN): only the *magnitude* of its outgoing
    recurrent weights is learned, the *sign* is fixed by cell type, exactly like SNN_LIFCell's
    recurrent_weights_dale masking (lif_refrac_cell.py). It also copies the SNN's readout
    convention: only excitatory units' activity reaches the linear readout (read_out_mask
    zeroing inhibitory units in the SNN) - inhibitory units still fully participate in the
    recurrent dynamics, they just don't project downstream. Keeping the same leak as VanillaRNN
    means this comparison isolates Dale's law as the one varying factor between the two vanilla
    models, rather than also silently reintroducing a leaky-vs-not confound."""

    def __init__(self, input_size, hidden_size, output_size, loss_step, alpha, rho=2.5, ei_ratio=0.8):
        super().__init__()
        self.hidden_size = hidden_size
        self.exc_size = int(hidden_size * ei_ratio)
        self.loss_step = loss_step
        self.alpha = alpha  # leak fraction per timestep, same convention as VanillaRNN
        self.recording = None  # populated on each forward() call, mirrors model.snn.recording

        self.input_weights = torch.nn.Parameter(torch.randn(hidden_size, input_size) / input_size ** 0.5)
        self.bias = torch.nn.Parameter(torch.zeros(hidden_size))
        self.recurrent_weights = torch.nn.Parameter(torch.empty(hidden_size, hidden_size))
        self.readout = torch.nn.Linear(hidden_size, output_size)

        with torch.no_grad():
            w = torch.randn(hidden_size, hidden_size) / hidden_size ** 0.5
            spectral_radius = torch.linalg.eigvals(w).abs().max()
            self.recurrent_weights.copy_(w * (rho / spectral_radius))

        # fixed sign per presynaptic unit: +1 excitatory, scaled negative inhibitory
        # (scaling balances total E vs I drive, same idea as the SNN's dale_vec)
        dale_sign = torch.ones(hidden_size)
        dale_sign[self.exc_size:] = -ei_ratio / (1 - ei_ratio)
        self.register_buffer('dale_sign', dale_sign)
        self.register_buffer('no_self_mask', 1 - torch.eye(hidden_size))

        readout_mask = torch.ones(hidden_size)
        readout_mask[self.exc_size:] = 0  # only excitatory units project downstream
        self.register_buffer('readout_mask', readout_mask)

    def effective_recurrent_weights(self):
        # magnitude only - Dale's law fixes the sign, gradient descent only learns |w|
        w = torch.abs(self.recurrent_weights) * self.no_self_mask
        return w * self.dale_sign.unsqueeze(0)

    def forward(self, x):
        seq_len, batch_size, _ = x.shape
        h = torch.zeros(batch_size, self.hidden_size, dtype=x.dtype, device=x.device)
        w_rec = self.effective_recurrent_weights()
        outputs, hs = [], []
        for t in range(seq_len):
            a = x[t] @ self.input_weights.T + h @ w_rec.T + self.bias
            candidate = torch.tanh(a)
            h = (1 - self.alpha) * h + self.alpha * candidate
            hs.append(h.detach())
            outputs.append(self.readout(h * self.readout_mask))
        out = torch.stack(outputs)                    # (seq_len, batch, output_size)
        self.recording = torch.stack(hs)               # (seq_len, batch, hidden_size), exposed for analysis
        return out[-self.loss_step:].transpose(1, 0)    # (batch, loss_step, output_size)

dale_hidden_size = vanilla_hidden_size  # match the plain vanilla RNN's size for a fair 3-way comparison

dale_model = VanillaRNNDale(
    input_size=5, hidden_size=dale_hidden_size, output_size=2, loss_step=loss_step,
    alpha=vanilla_alpha, rho=2.5, ei_ratio=model_parameters.lif.ei_ratio,
).to(device).double()

n_dale_params = sum(p.numel() for p in dale_model.parameters())
dale_exc_size = dale_model.exc_size
print(f"{n_dale_params} trainable parameters, {dale_hidden_size} hidden units "
      f"({dale_exc_size} excitatory / {dale_hidden_size - dale_exc_size} inhibitory)")

"""Optional: load checkpoint or skip to training"""

dale_ckpt_path = '/content/drive/MyDrive/vanilla_rnn_dale.pt'  # <-- update to wherever you have copied the checkpoint

dale_ckpt = torch.load(dale_ckpt_path, map_location=device, weights_only=False)

# reconstruct the exact architecture from the checkpoint's own config, rather than assuming
# it matches whatever hidden_size/alpha/ei_ratio happen to be set above
cfg = dale_ckpt['config']
dale_hidden_size = cfg['hidden_size']
dale_alpha = cfg['alpha']

dale_model = VanillaRNNDale(
    input_size=cfg['input_size'], hidden_size=dale_hidden_size, output_size=cfg['output_size'],
    loss_step=cfg.get('loss_step', loss_step), alpha=dale_alpha,
    rho=cfg.get('rho', 2.5), ei_ratio=cfg.get('ei_ratio', model_parameters.lif.ei_ratio),
).to(device).double()
dale_model.load_state_dict(dale_ckpt['model_state_dict'])
dale_model.eval()

n_dale_params = sum(p.numel() for p in dale_model.parameters())
dale_exc_size = dale_model.exc_size
print(f"loaded Vanilla+Dale RNN checkpoint from {dale_ckpt_path} "
      f"({dale_ckpt.get('model_class', 'VanillaRNNDale')}), {n_dale_params} trainable parameters, "
      f"{dale_hidden_size} hidden units ({dale_exc_size} excitatory / {dale_hidden_size - dale_exc_size} inhibitory), "
      f"alpha={dale_alpha:.3f}")

vanilla_epochs = 5    # match section 3's epochs for a fair comparison
vanilla_batch_num = 200   # match section 3's batch_num
vanilla_batch_size = 64
vanilla_lr = 1e-4
# reuses vanilla_data_loader / vanilla_epochs / vanilla_batch_num / vanilla_lr from section 5,
# so this is trained on the same data with the same budget as the plain vanilla RNN
dale_optimizer = torch.optim.Adam(dale_model.parameters(), lr=vanilla_lr)

def run_batch_dale(train: bool):
    trials, tgs, _ = vanilla_data_loader.get_batch()
    tgs = tgs.unsqueeze(1).repeat((1, loss_step, 1)).double()
    _, ground_truth = torch.max(tgs[:, -1], 1)
    trials, tgs, ground_truth = trials.to(device).double(), tgs.to(device), ground_truth.to(device)

    output = dale_model(trials)
    loss = torch.nn.functional.mse_loss(output, tgs)

    pred = torch.argmax(output[:, -1], 1)
    acc = (ground_truth == pred).float().mean().item()
    return loss, acc

dale_train_losses, dale_train_accs, dale_test_losses, dale_test_accs = [], [], [], []

for epoch in range(vanilla_epochs):
    dale_model.train()
    epoch_losses, epoch_accs = [], []
    for _ in range(vanilla_batch_num):
        dale_optimizer.zero_grad()
        loss, acc = run_batch_dale(train=True)
        loss.backward()
        dale_optimizer.step()
        epoch_losses.append(loss.item())
        epoch_accs.append(acc)

    dale_model.eval()
    with torch.no_grad():
        t_loss, t_acc = zip(*[run_batch_dale(train=False) for _ in range(10)])
        t_loss = [l.item() for l in t_loss]

    dale_train_losses.append(np.mean(epoch_losses))
    dale_train_accs.append(np.mean(epoch_accs))
    dale_test_losses.append(np.mean(t_loss))
    dale_test_accs.append(np.mean(t_acc))

    print(f'epoch {epoch+1:>3}/{vanilla_epochs}  train loss {dale_train_losses[-1]:.4f} acc {dale_train_accs[-1]:.2f}  |  '
          f'test loss {dale_test_losses[-1]:.4f} acc {dale_test_accs[-1]:.2f}')

"""# Analyses section

## Behavioural performance

general accuracy + per rule accuracy
"""

def evaluate_model_performance(model, data_loader_obj, n_batches=40, return_preds=False, input_noise_std=0.0):
    """Run a model over n_batches batches, return (per-trial correct bools, matching desc dicts).
    With return_preds=True, also return the raw (pred, ground_truth) arrays (e.g. for a confusion matrix).
    input_noise_std adds iid Gaussian noise to the input trials before they reach the model (robustness check)."""
    model.eval()
    all_pred, all_gt, all_desc = [], [], []
    with torch.no_grad():
        for _ in range(n_batches):
            trials, tgs, desc = data_loader_obj.get_batch()
            if input_noise_std > 0:
                trials = trials + input_noise_std * torch.randn_like(trials)
            tgs = tgs.unsqueeze(1).repeat((1, loss_step, 1)).double()
            _, ground_truth = torch.max(tgs[:, -1], 1)
            trials, ground_truth = trials.to(device).double(), ground_truth.to(device)

            output = model(trials)  # works for all three: SNN's forward also accepts (trials) alone
            pred = torch.argmax(output[:, -1], 1)

            all_pred.append(pred.cpu().numpy())
            all_gt.append(ground_truth.cpu().numpy())
            all_desc.extend(desc)

    all_pred = np.concatenate(all_pred)
    all_gt = np.concatenate(all_gt)
    if return_preds:
        return all_pred == all_gt, all_desc, all_pred, all_gt
    return all_pred == all_gt, all_desc


# consistent color per model across every panel in this comparison (Okabe-Ito colorblind-safe triple)
MODEL_COLORS = {'SNN': '#0072B2', 'Vanilla RNN': '#E69F00', 'Vanilla + Dale': '#009E73'}
models_to_compare = [
    ('SNN', model, data_loader),
    ('Vanilla RNN', vanilla_model, vanilla_data_loader),
    ('Vanilla + Dale', dale_model, vanilla_data_loader),
]

overall_acc = {}
rule_acc = {}
congruency_acc = {}
for name, m, dl in models_to_compare:
    correct, desc = evaluate_model_performance(m, dl, n_batches=40)
    overall_acc[name] = correct.mean()
    rule_acc[name] = {
        'audio-context (c=0)': np.array([c for c, d in zip(correct, desc) if d['c'] == 0]).mean(),
        'visual-context (c=1)': np.array([c for c, d in zip(correct, desc) if d['c'] == 1]).mean(),
    }
    # congruent: the cued and uncued modality indicate the same side; incongruent: they conflict.
    # a model that isn't fully gating out the irrelevant channel should do worse on incongruent trials.
    congruency_acc[name] = {
        'congruent (aud==light)': np.array([c for c, d in zip(correct, desc) if d['aud'] == d['light']]).mean(),
        'incongruent (aud!=light)': np.array([c for c, d in zip(correct, desc) if d['aud'] != d['light']]).mean(),
    }
    print(f"{name:<16} overall {overall_acc[name]:.1%}  |  "
          f"audio-rule {rule_acc[name]['audio-context (c=0)']:.1%}  "
          f"visual-rule {rule_acc[name]['visual-context (c=1)']:.1%}  |  "
          f"congruent {congruency_acc[name]['congruent (aud==light)']:.1%}  "
          f"incongruent {congruency_acc[name]['incongruent (aud!=light)']:.1%}")

"""confusion matrices"""

LABELS = ['Right', 'Left']

fig, axes = plt.subplots(1, len(models_to_compare), figsize=(4.5 * len(models_to_compare), 4),
                          gridspec_kw={'wspace': 0.55})
for ax, (name, m, dl) in zip(axes, models_to_compare):
    _, _, pred, gt = evaluate_model_performance(m, dl, n_batches=40, return_preds=True)

    conf = np.zeros((2, 2), dtype=int)
    for g, p in zip(gt, pred):
        conf[g, p] += 1
    conf_norm = conf / conf.sum(axis=1, keepdims=True)

    im = ax.imshow(conf_norm, cmap='Blues', vmin=0, vmax=1)
    for r in range(2):
        for c in range(2):
            ax.text(c, r, f'{conf[r, c]}\n({conf_norm[r, c]:.0%})', ha='center', va='center',
                    color='white' if conf_norm[r, c] > 0.5 else 'black', fontsize=9)
    ax.set_xticks([0, 1]); ax.set_xticklabels([f'pred {l}' for l in LABELS])
    ax.set_yticks([0, 1]); ax.set_yticklabels([f'true {l}' for l in LABELS])
    ax.set_title(name, color=MODEL_COLORS[name], fontweight='bold')

fig.colorbar(im, ax=axes, fraction=0.025, pad=0.02, label='fraction of true class')
plt.show()

# confusion matrices split by rule (audio-context vs visual-context), 2 rows x 3 columns -
# the pooled version above averages over both cues, hiding any per-rule bias pattern
fig, axes = plt.subplots(2, len(models_to_compare), figsize=(4.5 * len(models_to_compare), 8),
                          gridspec_kw={'wspace': 0.55, 'hspace': 0.5})

im = None
for col, (name, m, dl) in enumerate(models_to_compare):
    _, desc, pred, gt = evaluate_model_performance(m, dl, n_batches=40, return_preds=True)

    for row, rule in enumerate((0, 1)):
        idx = [i for i, d in enumerate(desc) if d['c'] == rule]
        conf = np.zeros((2, 2), dtype=int)
        for i in idx:
            conf[gt[i], pred[i]] += 1
        conf_norm = conf / conf.sum(axis=1, keepdims=True)

        ax = axes[row, col]
        im = ax.imshow(conf_norm, cmap='Blues', vmin=0, vmax=1)
        for r in range(2):
            for c in range(2):
                ax.text(c, r, f'{conf[r, c]}\n({conf_norm[r, c]:.0%})', ha='center', va='center',
                        color='white' if conf_norm[r, c] > 0.5 else 'black', fontsize=9)
        ax.set_xticks([0, 1]); ax.set_xticklabels([f'pred {l}' for l in LABELS])
        ax.set_yticks([0, 1]); ax.set_yticklabels([f'true {l}' for l in LABELS])
        if row == 0:
            ax.set_title(name, color=MODEL_COLORS[name], fontweight='bold')
        if col == 0:
            rule_label = 'audio-context' if rule == 0 else 'visual-context'
            ax.annotate(rule_label, xy=(-0.65, 0.5), xycoords='axes fraction',
                        rotation=90, ha='center', va='center', fontsize=10, fontweight='bold')

fig.colorbar(im, ax=axes, fraction=0.02, pad=0.02, label='fraction of true class')
plt.show()

"""## Generalization

### longer delay periods
"""

delay_values = [0.4, 0.8, 1.2, 1.6]  # trained delay is 0.4s; the rest are unseen generalization tests

delay_acc = {name: [] for name, _, _ in models_to_compare}
for delay in delay_values:
    ts = dict(trial_setting)
    ts['cueing_delay'] = delay
    delay_loader = DataGenerator(64, trial_setting=ts, p=LIFParameters(), cueing_context_num=1, dt=dt)
    delay_loader.generate_all_trials()

    row = []
    for name, m, _ in models_to_compare:
        correct, _ = evaluate_model_performance(m, delay_loader, n_batches=10)
        delay_acc[name].append(correct.mean())
        row.append(f'{name}={correct.mean():.1%}')
    print(f'delay={delay:.1f}s  ' + '  '.join(row))

fig, axes = plt.subplots(1, 3, figsize=(16, 4.5))
names = [n for n, _, _ in models_to_compare]
colors = [MODEL_COLORS[n] for n in names]

# panel 1: overall accuracy
vals = [overall_acc[n] for n in names]
bars = axes[0].bar(names, vals, color=colors, width=0.6)
axes[0].bar_label(bars, labels=[f'{v:.0%}' for v in vals], padding=3)
axes[0].axhline(0.5, color='gray', linestyle=':', linewidth=1)
axes[0].set_ylim(0, 1.08)
axes[0].set_ylabel('accuracy')
axes[0].set_title('overall accuracy')

# panel 2: accuracy by rule (grouped bar)
rules = ['audio-context (c=0)', 'visual-context (c=1)']
x = np.arange(len(rules))
width = 0.25
for i, name in enumerate(names):
    v = [rule_acc[name][r] for r in rules]
    axes[1].bar(x + (i - 1) * width, v, width, label=name, color=MODEL_COLORS[name])
axes[1].set_xticks(x)
axes[1].set_xticklabels(['audio rule', 'visual rule'])
axes[1].axhline(0.5, color='gray', linestyle=':', linewidth=1)
axes[1].set_ylim(0, 1.08)
axes[1].set_title('accuracy by rule')
axes[1].legend(fontsize=8, frameon=False)

# panel 3: generalization to longer delays (line)
for name in names:
    axes[2].plot(delay_values, delay_acc[name], marker='o', linewidth=2, label=name, color=MODEL_COLORS[name])
axes[2].axvline(trial_setting['cueing_delay'], color='gray', linestyle='--', linewidth=1)
axes[2].axhline(0.5, color='gray', linestyle=':', linewidth=1)
axes[2].set_ylim(0, 1.08)
axes[2].set_xlabel('cueing_delay (s)')
axes[2].set_title('generalization to longer delays')
axes[2].legend(fontsize=8, frameon=False)

for ax in axes:
    ax.spines['top'].set_visible(False)
    ax.spines['right'].set_visible(False)

plt.tight_layout()
plt.show()

"""### robustness to input noise"""

noise_levels = [0.0, 0.05, 0.1, 0.2, 0.3, 0.5]

noise_acc = {name: [] for name, _, _ in models_to_compare}
for noise in noise_levels:
    row = []
    for name, m, dl in models_to_compare:
        correct, _ = evaluate_model_performance(m, dl, n_batches=20, input_noise_std=noise)
        noise_acc[name].append(correct.mean())
        row.append(f'{name}={correct.mean():.1%}')
    print(f'input_noise_std={noise:.2f}  ' + '  '.join(row))

fig, ax = plt.subplots(figsize=(7.5, 4.5))
for name, _, _ in models_to_compare:
    ax.plot(noise_levels, noise_acc[name], marker='o', linewidth=2, label=name, color=MODEL_COLORS[name])

ax.axhline(0.5, color='gray', linestyle=':', linewidth=1, label='chance')
ax.set_xlabel('input noise std')
ax.set_ylabel('accuracy')
ax.set_ylim(0, 1.08)
ax.set_title('robustness to input noise')
ax.legend(fontsize=8, frameon=False)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

plt.tight_layout()
plt.show()

"""### robustness to dropout"""

# self-contained model list (doesn't depend on the later Rule-Specific section's rule_model_info)
drop_model_info = [
    ('SNN', model, data_loader, True),
    ('Vanilla RNN', vanilla_model, vanilla_data_loader, False),
    ('Vanilla + Dale', dale_model, vanilla_data_loader, False),
]


def get_readout_weight(m, is_snn):
    """The (2, hidden_size) linear-readout weight matrix, wherever it lives for this architecture.
    For the SNN, fc_out lives on the inner .snn module - model itself is just the Model() wrapper."""
    return m.snn.fc_out.weight if is_snn else m.readout.weight


def evaluate_with_dropped_units(m, dl, is_snn, drop_frac, n_batches=20):
    """Zero out drop_frac of hidden units' columns in the readout weight, evaluate accuracy, then restore -
    a simplified, architecture-uniform stand-in for the paper's synaptic-weight lesioning (see markdown above)."""
    w = get_readout_weight(m, is_snn)
    hidden_size = w.shape[1]
    n_drop = int(round(drop_frac * hidden_size))
    original = w.detach().clone()
    if n_drop > 0:
        drop_idx = np.random.choice(hidden_size, size=n_drop, replace=False)
        with torch.no_grad():
            w[:, drop_idx] = 0
    correct, _ = evaluate_model_performance(m, dl, n_batches=n_batches)
    with torch.no_grad():
        w.copy_(original)
    return correct.mean()


drop_fracs = [0.0, 0.1, 0.2, 0.3, 0.4, 0.5]
n_repeats = 10  # matches the paper's "SD across 10 random realizations"

drop_acc_mean = {name: [] for name, *_ in drop_model_info}
drop_acc_std = {name: [] for name, *_ in drop_model_info}

for frac in drop_fracs:
    row = []
    for name, m, dl, is_snn in drop_model_info:
        reps = [evaluate_with_dropped_units(m, dl, is_snn, frac) for _ in range(n_repeats if frac > 0 else 1)]
        drop_acc_mean[name].append(np.mean(reps))
        drop_acc_std[name].append(np.std(reps))
        row.append(f'{name}={drop_acc_mean[name][-1]:.1%}±{drop_acc_std[name][-1]:.1%}')
    print(f'drop_frac={frac:.1f}  ' + '  '.join(row))

fig, ax = plt.subplots(figsize=(7.5, 4.5))
for name, *_ in drop_model_info:
    mean, std = np.array(drop_acc_mean[name]), np.array(drop_acc_std[name])
    ax.plot(drop_fracs, mean, marker='o', linewidth=2, label=name, color=MODEL_COLORS[name])
    ax.fill_between(drop_fracs, mean - std, mean + std, color=MODEL_COLORS[name], alpha=0.15)

ax.axhline(0.5, color='gray', linestyle=':', linewidth=1, label='chance')
ax.set_xlabel('fraction of hidden units dropped from the readout')
ax.set_ylabel('accuracy')
ax.set_ylim(0, 1.08)
ax.set_title('robustness to unit dropping (mean ± SD, 10 realizations)')
ax.legend(fontsize=8, frameon=False)
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

plt.tight_layout()
plt.show()

"""## 2D PCA population trajectories"""

from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold, cross_val_score


def bin_average(x, bin_size):
    """x: (seq_len, ...) -> (seq_len // bin_size, ...), averaged within each bin."""
    n_bins = x.shape[0] // bin_size
    x = x[:n_bins * bin_size]
    return x.reshape((n_bins, bin_size) + x.shape[1:]).mean(axis=1)


def get_activity(m, is_snn):
    """Most recent forward pass's (seq_len, batch, hidden_size) hidden activity:
    raw spikes for the SNN, raw tanh activation for the vanilla models."""
    return m.snn.recording.lif0.z.cpu().numpy() if is_snn else m.recording.cpu().numpy()


DELAY_START = int((trial_setting['fixation'] + trial_setting['cueing']) // dt)
DELAY_END = DELAY_START + int(trial_setting['cueing_delay'] // dt)
BIN_SIZE = 10  # 10 steps * dt=0.002s = 20ms bins

from sklearn.decomposition import PCA
import matplotlib.patches as mpatches
from matplotlib.lines import Line2D


def condition_delay_traces(m, data_loader_obj, is_snn, n_batches=60):
    """Trial-averaged, delay-period, time-binned activity per unit, split by (rule, choice) -
    4 conditions: rule (audio/visual context) x choice (correct side/ground truth), matching
    the paper's Rule x Choice population-trajectory analysis (results_visualization.py's get_pca)."""
    m.eval()
    sums = {(c, t): None for c in (0, 1) for t in (0, 1)}
    counts = {(c, t): 0 for c in (0, 1) for t in (0, 1)}
    with torch.no_grad():
        for _ in range(n_batches):
            trials, _, desc = data_loader_obj.get_batch()
            _ = m(trials.to(device).double())
            act = bin_average(get_activity(m, is_snn)[DELAY_START:DELAY_END], BIN_SIZE)  # (bins, batch, hidden)
            for i, d in enumerate(desc):
                key = (d['c'], d['truth'])
                s = act[:, i, :]
                sums[key] = s if sums[key] is None else sums[key] + s
                counts[key] += 1
    return {key: sums[key] / counts[key] for key in sums}  # each (bins, hidden_size)


CONDITIONS = [(0, 0), (0, 1), (1, 0), (1, 1)]  # (rule, choice)
RULE_COLOR = {0: 'tab:blue', 1: 'tab:red'}
CHOICE_STYLE = {0: '-', 1: '--'}

traj_model_info = [
    ('SNN', model, data_loader, True, slice(0, int(model.snn.hidden_size * model.snn.ei_ratio))),
    ('Vanilla RNN', vanilla_model, vanilla_data_loader, False, slice(0, vanilla_model.hidden_size)),
    ('Vanilla + Dale', dale_model, vanilla_data_loader, False, slice(0, dale_model.exc_size)),
]

fig, axes = plt.subplots(1, len(traj_model_info), figsize=(5.5 * len(traj_model_info), 5))
for ax, (name, m, dl, is_snn, exc_slice) in zip(axes, traj_model_info):
    traces = condition_delay_traces(m, dl, is_snn)
    pooled = np.vstack([traces[k][:, exc_slice] for k in CONDITIONS])
    pca = PCA(n_components=2)
    pca.fit(pooled)

    for rule, choice in CONDITIONS:
        proj = pca.transform(traces[(rule, choice)][:, exc_slice])
        proj = proj - proj[0]  # every trajectory starts at the origin
        ax.plot(proj[:, 0], proj[:, 1], color=RULE_COLOR[rule], linestyle=CHOICE_STYLE[choice], alpha=0.7)
        ax.scatter(proj[:, 0], proj[:, 1], color=RULE_COLOR[rule], alpha=0.7, s=15)
        ax.scatter(proj[-1, 0], proj[-1, 1], color=RULE_COLOR[rule], marker='o', s=70, zorder=3)

    ax.scatter(0, 0, marker='x', color='m', s=80, zorder=3)
    ax.set_title(name, color=MODEL_COLORS[name], fontweight='bold')
    ax.set_xlabel('PC1'); ax.set_ylabel('PC2')

legend_handles = [
    mpatches.Patch(color='tab:blue', alpha=0.7, label='Rule 1 (audio)'),
    mpatches.Patch(color='tab:red', alpha=0.7, label='Rule 2 (visual)'),
    Line2D([0], [0], color='black', linestyle='-', alpha=0.7, label='Choice 1 (Right)'),
    Line2D([0], [0], color='black', linestyle='--', alpha=0.7, label='Choice 2 (Left)'),
]
fig.legend(handles=legend_handles, loc='upper center', ncol=4, bbox_to_anchor=(0.5, 1.08), frameon=False)

plt.tight_layout()
plt.show()

"""## Fixed point finding

For vanilla RNNs (with/without Dale's Law constraint) only
"""

FIXED_POINTS_DIR = '/content/drive/MyDrive/'  # <-- update to wherever you upload fixed_points.py
if FIXED_POINTS_DIR not in sys.path:
    sys.path.insert(0, FIXED_POINTS_DIR)
import fixed_points

# fixed_points.py assumes float32 throughout, but vanilla_model/dale_model are float64 to match the SNN. Extract weights as float32
# copies here rather than editing fixed_points.py, so the rest of the module needs no changes.

def vanilla_rnn_step_fun_f32(model, x_star):
    """Step-function builder for VanillaRNN (has a torch.nn.RNN submodule)."""
    w_ih = model.rnn.weight_ih_l0.detach().float()
    w_hh = model.rnn.weight_hh_l0.detach().float()
    b_ih = model.rnn.bias_ih_l0.detach().float()
    b_hh = model.rnn.bias_hh_l0.detach().float()
    x_star = x_star.detach().float()

    def rnn_fun(h):
        return torch.tanh(w_ih @ x_star + b_ih + w_hh @ h + b_hh)
    return rnn_fun


def dale_rnn_step_fun_f32(model, x_star):
    """Step-function builder for VanillaRNNDale (hand-rolled recurrence, no .rnn submodule)."""
    w_in = model.input_weights.detach().float()
    w_rec = model.effective_recurrent_weights().detach().float()
    b = model.bias.detach().float()
    x_star = x_star.detach().float()

    def rnn_fun(h):
        return torch.tanh(w_in @ x_star + b + w_rec @ h)
    return rnn_fun


# Fixed-point optimization hyperparameters -- start from the module defaults
# and override as needed (num_batches reduced here for faster iteration).
fp_hps = dict(fixed_points.DEFAULT_FP_HPS)
fp_hps.update({
    'num_batches': 2000,
    'opt_print_every': 200,
})

n_candidates = 500          # number of candidate hidden states to optimize per model
x_star = torch.zeros(5)     # fixed input condition (autonomous dynamics)


def collect_candidates(model, n_candidates=n_candidates):
    """Candidate hidden states: run model on one batch of real trials (from this
    notebook's vanilla_data_loader, matching the Training vanilla RNN section),
    flatten across time and trials, then randomly subsample."""
    model.eval()
    with torch.no_grad():
        cand_inputs, _, _ = vanilla_data_loader.get_batch()
        cand_inputs = cand_inputs.double().to(device)
        _ = model(cand_inputs)
        cand_hidden = model.recording.reshape(-1, model.recording.shape[-1]).detach().cpu().numpy()
    rand_idx = np.random.choice(cand_hidden.shape[0], size=min(n_candidates, cand_hidden.shape[0]), replace=False)
    return cand_hidden[rand_idx]

fp_models = {
    'Vanilla RNN': (vanilla_model, vanilla_rnn_step_fun_f32),
    'Vanilla + Dale': (dale_model, dale_rnn_step_fun_f32),
}

fp_results = {}
for name, (m, step_fun_builder) in fp_models.items():
    print(f'--- {name} ---')
    candidates = collect_candidates(m)
    rnn_fun = step_fun_builder(m, x_star.to(device))
    fps, losses, keep_idxs, opt_details = fixed_points.find_fixed_points(
        rnn_fun, candidates, fp_hps, device=device)
    fp_results[name] = {'fps': fps, 'losses': losses, 'rnn_fun': rnn_fun}
    print(f'Found {len(fps)} fixed points.\n')

"""## Decoding"""

DECODING_DIR = '/content/drive/MyDrive'  # <-- update to wherever you upload decoding.py
if DECODING_DIR not in sys.path:
    sys.path.insert(0, DECODING_DIR)
from decoding import run_decoding_pipeline, generate_noisy_trials
noisy_trials = generate_noisy_trials(data_loader, n_repeats=50, noise_std=0.05, seed=0)
vanilla_decoding = run_decoding_pipeline(vanilla_model, 'vanilla_rnn', data_loader, dt, trial_setting, noisy_trials=noisy_trials, device=device)
# dale_decoding = run_decoding_pipeline(dale_model, 'vanilla_rnn_dale', data_loader, dt, trial_setting, noisy_trials=noisy_trials, device=device)
plt.show()

snn_decoding = run_decoding_pipeline(model, 'snn', data_loader, dt, trial_setting, noisy_trials=noisy_trials, device=device)